<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Viaja a los mejores hoteles de Cancún, la Riviera Maya, República Dominicana y más. Kaaxtik Travel es la única agencia certificada para canjear su certificado de vacaciones.">
    <meta name="keywords" content="Viajes, viajes largos, viajes cortos, promociones, paquetes, tours, circuitos, paquetes hotel más avión, hoteles con ofertas, meses sin intereses, vuelos económicos, experiencias VIP, Tarjetas de regalo, certificados de regalo, regalo virtual.">
    <title>Paradisus Cancún</title>

    <!-- Favicons-->
    <link rel="shortcut icon" href="img/favicon.png" type="image/x-icon">
    <link rel="apple-touch-icon" type="image/x-icon" href="img/apple-touch-icon-57x57-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="img/apple-touch-icon-72x72-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="img/apple-touch-icon-114x114-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="img/apple-touch-icon-144x144-precomposed.png">

    <!-- GOOGLE WEB FONT -->
    <link href="https://fonts.googleapis.com/css2?family=Gochi+Hand&family=Montserrat:wght@300;400;500;600;700&display=swap" rel="stylesheet">

    <!-- COMMON CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
    <link href="css/vendors.css" rel="stylesheet">

    <!-- CUSTOM CSS -->
    <link href="css/custom.css" rel="stylesheet">

</head>

<body>

    <?php include("template/navbar.php") ?>
    <!-- End Header -->

    <section class="parallax-window" data-parallax="scroll" data-image-src="img/slider_single_tour/Paradisus/image-1.jpeg" data-natural-width="1400" data-natural-height="470">
        <div class="parallax-content-2">
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <span class="rating"><i class="icon-star voted"></i><i class="icon-star voted"></i><i class="icon-star voted"></i><i class="icon-star voted"></i><i class=" icon-star-empty"></i></span>
                        <h1>Paradisus Cancún</h1>
                    </div>
                    <div class="col-md-1">
                    </div>
                    <div class="col-md-3">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End section -->

    <main>
        <div id="position">
            <div class="container">
                <ul>
                    <li><a href="#">Destinos</a>
                    </li>
                    <li><a href="cancun.php">Cancún</a>
                    </li>
                    <li>Paradisus Cancún</li>
                </ul>
            </div>
        </div>
        <!-- End Position -->

        <div class="collapse" id="collapseMap">
            <div id="map" class="map"></div>
        </div>
        <!-- End Map -->

        <div class="container margin_60">
            <div class="row">
                <div class="col-lg-8" id="single_tour_desc">
                    <div id="single_tour_feat">
                        <ul>
                            <li><i class="icon_set_2_icon-116"></i>TV Flatscreen</li>
                            <li><i class="icon_set_1_icon-86"></i>Wifi</li>
                            <li><i class="icon_set_2_icon-110"></i>Picina</li>
                            <li><i class="icon_set_2_icon-108"></i>En la Playa</li>
                            <li><i class="icon_set_1_icon-13"></i>Accesibilidad</li>
                            <li><i class="icon_set_1_icon-58"></i>Todo Incluido</li>
                        </ul>
                    </div>
                    <!-- Map button for tablets/mobiles -->
                    <div id="Img_carousel" class="slider-pro">
                        <div class="sp-slides">
                            <div class="sp-slide">
                                <img alt="Image" class="sp-image" src="css/images/blank.gif" data-src="img/slider_single_tour/Paradisus/image-1.jpeg">
                            </div>
                            <div class="sp-slide">
                                <img alt="Image" class="sp-image" src="css/images/blank.gif" data-src="img/slider_single_tour/Paradisus/image-2.jpeg">
                            </div>

                            <div class="sp-slide">
                                <img alt="Image" class="sp-image" src="css/images/blank.gif" data-src="img/slider_single_tour/Paradisus/image-3.jpeg">
                            </div>

                            <div class="sp-slide">
                                <img alt="Image" class="sp-image" src="css/images/blank.gif" data-src="img/slider_single_tour/Paradisus/image-4.jpeg">
                            </div>

                            <div class="sp-slide">
                                <img alt="Image" class="sp-image" src="css/images/blank.gif" data-src="img/slider_single_tour/Paradisus/image-5.jpeg">
                            </div>

                            <div class="sp-slide">
                                <img alt="Image" class="sp-image" src="css/images/blank.gif" data-src="img/slider_single_tour/Paradisus/image-6.jpeg">
                            </div>

                            <div class="sp-slide">
                                <img alt="Image" class="sp-image" src="css/images/blank.gif" data-src="img/slider_single_tour/Paradisus/image-7.jpeg">
                            </div>

                            <div class="sp-slide">
                                <img alt="Image" class="sp-image" src="css/images/blank.gif" data-src="img/slider_single_tour/Paradisus/image-8.jpeg">
                            </div>
                        </div>
                        <div class="sp-thumbnails">
                            <img alt="Image" class="sp-thumbnail" src="img/slider_single_tour/Paradisus/image-1.jpeg">
                            <img alt=" Image " class="sp-thumbnail " src="img/slider_single_tour/Paradisus/image-2.jpeg">
                            <img alt="Image " class="sp-thumbnail " src="img/slider_single_tour/Paradisus/image-3.jpeg">
                            <img alt="Image " class="sp-thumbnail " src="img/slider_single_tour/Paradisus/image-4.jpeg">
                            <img alt="Image " class="sp-thumbnail " src="img/slider_single_tour/Paradisus/image-5.jpeg">
                            <img alt="Image " class="sp-thumbnail " src="img/slider_single_tour/Paradisus/image-6.jpeg">
                            <img alt="Image " class="sp-thumbnail " src="img/slider_single_tour/Paradisus/image-7.jpeg">
                            <img alt="Image " class="sp-thumbnail " src="img/slider_single_tour/Paradisus/image-8.jpeg">
                        </div>
                    </div>

                    <hr>

                    <div class="row ">
                        <div class="col-lg-3 ">
                            <h3>Paradisus Cancún</h3>
                        </div>
                        <div class="col-lg-9 ">
                            <p>
                                Disfruta la belleza de Cancún con todos tus sentidos. Abre tu corazón a toda la belleza del mar Caribe en este lujoso resort todo incluido. La espectacular arquitectura, las influencias de la cultura maya y la espectacular atención al detalle y los servicios
                                exclusivos son diferentes a todo lo que hayas experimentado. Las impresionantes ventanas de vidrio aseguran que tu suite esté bañada por la luz natural del Caribe.
                            </p>

                            <p>
                                Descubre el máximo bienestar en nuestro fabuloso YHI Spa, así como todas las posibilidades de Cancún desde este alojamiento rico en tradición, lujo y diversión. Descubre los servicios superiores de The Reserve (+18 años) y Nikté, diseñados para elevar
                                el lujo de tus vacaciones, ofreciendo beneficios exclusivos.
                            </p>

                            <p>
                                También te sorprenderá el equilibrio perfecto entre la exuberante naturaleza y las tradiciones locales: disfruta de maravillosas puestas de sol desde tu habitación. Podrás disfrutar de los más exquisitos servicios durante tu estadía para que todo salga
                                exactamente como lo soñaste. Una increíble selección de platillos y sabores del mundo te esperan. Snorkel, buceo, explorar el arrecife y los cenotes... un sinfín de actividades para descubrir la esencia de Cancún.
                            </p>

                            <!-- <h4>Comodidades de hotel</h4> -->
                            <p>


                                <!-- 
									<div class="row ">
										<div class="col-md-6 ">
											<ul class="list_ok ">
												<li>Baño privado</li>
												<li>Televisión</li>
												<li>Limpieza de habitaciones diaria</li>
											</ul>
										</div>
										<div class="col-md-6 ">
											<ul class="list_ok ">
												<li>Plancha y tabla de planchar</li>
												<li>Secadora de cabello</li>
												<li>Cortinas blackout</li>
											</ul>
										</div>
									</div>
								 -->

                                <!-- End row  -->
                        </div>
                        <!-- End col-md-9  -->
                    </div>
                    <!-- End row  -->

                </div>
                <!--End  single_tour_desc-->

                <aside class="col-md-4 ">
                    <div class="box_style_1 ">
                        <span class="tape "></span>
                        <h4>Preguntas <span><i class="icon-help pull-right "></i></span></h4>
                        <p>
                            Visite nuestra sección de Preguntas frecuentes para ver las respuestas a las preguntas y dudas expresadas por clientes anteriores haciendo click aqui:
                            <a href="preguntas.php ">Preguntas Frecuentes</a>
                        </p>
                        <ul id="contact-info ">
                            <li>+52 998 407 7963</li>
                            <li><a href="mailto:info@kaaxtiktravel.com ">info@kaaxtiktravel.com</a>
                            </li>
                        </ul>
                    </div>


                    <div class="box_style_1 ">
                        <span class="tape "></span>
                        <h3><strong><i class="icon_set_1_icon-23 "></i></strong>Destinos</h3>

                        <h4><i class="icon_set_1_icon-41 "></i><a href="cancun.php "> Cancún  </a></h4>
                        <h4><i class="icon_set_1_icon-41 "></i><a href="vallarta.php ">Puerto Vallarta</a></h4>
                        <h4><i class="icon_set_1_icon-41 "></i><a href="cabos.php ">Los Cabos</a></h4>
                        <h4><i class="icon_set_1_icon-41 "></i><a href="riviera.php ">Riviera Maya</a></h4>
                        <h4><i class="icon_set_1_icon-41 "></i><a href="ixtapa.php ">Ixtapa</a></h4>
                        <h4><i class="icon_set_1_icon-41 "></i><a href="huatulco.php ">Huatulco</a></h4>
                        <h4><i class="icon_set_1_icon-41 "></i><a href="acapulco.php ">Acapulco</a></h4>
                        <h4><i class="icon_set_1_icon-41 "></i><a href="republica.php ">Republica Dominicana</a></h4>
                        <h4><i class="icon_set_1_icon-41 "></i><a href="panama.php ">Panamá</a></h4>
                        <h4><i class="icon_set_1_icon-41 "></i><a href="curacao.php ">Curacao</a></h4>
                    </div>


                    <!--End step -->

                    <div class="box_style_4 ">

                        <i class="icon_set_1_icon-57 "></i>
                        <h4>¿Necesitas <span> ayuda? </span></h4>
                        <a href="tel://+529984077963 " class="phone ">+52  998 407 7963</a>
                        <small>Lunes a Viernes 9.00 a 19.30 hrs.</small>
                    </div>

                    <a class="btn_full_outline " href="contact.php "><i class="icon_set_1_icon-85 "></i> Contáctanos</a>

            </div>
            <!-- End col-md-4 -->

            </aside>
        </div>
        <!--End row -->
        </div>
        <!--End container -->

        <div id="overlay "></div>
        <!-- Mask on input focus -->

    </main>
    <!-- End main -->

    <?php include("template/navbar.php") ?>
    <!-- End footer -->

    <div id="toTop "></div>
    <!-- Back to top button -->

    <!-- Common scripts -->
    <script src="js/jquery-3.5.1.min.js "></script>
    <script src="js/common_scripts_min.js "></script>
    <script src="js/functions.js "></script>

    <!-- Date and time pickers -->
    <script src="js/jquery.sliderPro.min.js "></script>
    <script type="text/javascript ">
        $(document).ready(function($) {
            $('#Img_carousel').sliderPro({
                width: 960,
                height: 500,
                fade: true,
                arrows: true,
                buttons: false,
                fullScreen: false,
                smallSize: 500,
                startSlide: 0,
                mediumSize: 1000,
                largeSize: 3000,
                thumbnailArrows: true,
                autoplay: false
            });
        });
    </script>

    <!-- Date and time pickers -->
    <script>
        $('input.date-pick').datepicker('setDate', 'today');
    </script>

    <!-- Map -->
    <script src="http://maps.googleapis.com/maps/api/js "></script>
    <script src="js/map.js "></script>
    <script src="js/infobox.js "></script>

    <!-- Carousel -->
    <script>
        $('.carousel-thumbs-2').owlCarousel({
            loop: false,
            margin: 5,
            responsiveClass: true,
            nav: false,
            responsive: {
                0: {
                    items: 1
                },
                600: {
                    items: 3
                },
                1000: {
                    items: 4,
                    nav: false
                }
            }
        });
    </script>

    <!--Review modal validation -->
    <script src="assets/validate.js "></script>


</body>

</html>